### ISSUE TITLE
Module can cause endless loop

### ISSUE THREAD

**Issue by amenk** [integer-net/magento2-shippingpreselection#1]
The module can easily cause an endless lopp.

We use 

        return $this->session->getQuote()->getAllItems();

in our custom shipping calculator.

So 

    private function prepareShippingAddress(Quote $quote): Quote
    {
        $address = $quote->getShippingAddress();

causes a recursion on our case

We are evaluationg this further...

**Comment by schmengler** [comment]
Thank you, please keep us posted!

**Comment by amenk** [comment]
In the end of the day our custom shipping calculator might not be that cleanly implemented - it should use the items from the raterequest ...

**Comment by amenk** [comment]
We were able to fix this on our side (without a change in this module)
